-- Run this entire script in Supabase:
-- SQL Editor > New query > paste > Run

create table if not exists public.contracts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    contract_name text not null,
    contract_type text not null,
    offer_group text,
    system_name text,
    total_payout numeric not null check (total_payout > 0),
    salvage_value numeric not null default 0 check (salvage_value >= 0),
    expenses numeric not null default 0 check (expenses >= 0),
    crew_members integer not null default 1 check (crew_members >= 1),
    net_payout numeric not null,
    individual_share numeric not null,
    notes text
);

create table if not exists public.ore_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    action text not null check (action in ('Mined', 'Bought', 'Sold')),
    ore_name text not null,
    quantity_scu numeric not null default 0 check (quantity_scu >= 0),
    total_value numeric not null default 0 check (total_value >= 0),
    location text,
    notes text

);

-- Safe upgrades for existing deployments
alter table public.contracts
    add column if not exists salvage_value numeric not null default 0;

alter table public.contracts
    drop constraint if exists contracts_salvage_value_check;

alter table public.contracts
    add constraint contracts_salvage_value_check
    check (salvage_value >= 0);

alter table public.ore_transactions
    add column if not exists quantity_scu numeric not null default 0;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_total_value_check;

alter table public.ore_transactions
    add constraint ore_transactions_total_value_check
    check (total_value >= 0);

alter table public.ore_transactions
    drop constraint if exists ore_transactions_quantity_scu_check;

alter table public.ore_transactions
    add constraint ore_transactions_quantity_scu_check
    check (quantity_scu >= 0);

create index if not exists contracts_user_id_idx
    on public.contracts(user_id);

create index if not exists contracts_date_saved_idx
    on public.contracts(date_saved desc);

create index if not exists ore_transactions_user_id_idx
    on public.ore_transactions(user_id);

create index if not exists ore_transactions_date_saved_idx
    on public.ore_transactions(date_saved desc);

alter table public.contracts enable row level security;
alter table public.ore_transactions enable row level security;

drop policy if exists "Users can read own contracts" on public.contracts;
drop policy if exists "Users can insert own contracts" on public.contracts;
drop policy if exists "Users can update own contracts" on public.contracts;
drop policy if exists "Users can delete own contracts" on public.contracts;

create policy "Users can read own contracts"
on public.contracts
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own contracts"
on public.contracts
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own contracts"
on public.contracts
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own contracts"
on public.contracts
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own ore entries"
on public.ore_transactions;

drop policy if exists "Users can insert own ore entries"
on public.ore_transactions;

drop policy if exists "Users can update own ore entries"
on public.ore_transactions;

drop policy if exists "Users can delete own ore entries"
on public.ore_transactions;

create policy "Users can read own ore entries"
on public.ore_transactions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own ore entries"
on public.ore_transactions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own ore entries"
on public.ore_transactions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own ore entries"
on public.ore_transactions
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Blueprint tracker
begin;

create table if not exists public.blueprint_tracker (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    blueprint_name text not null,
    blueprint_category text not null default 'Other',
    blueprint_status text not null default 'Owned',
    source_location text,
    copies_owned integer not null default 1,
    target_builds integer not null default 1,
    materials jsonb not null default '{}'::jsonb,
    notes text
);

-- Repair partially created tables from an earlier migration.
alter table public.blueprint_tracker
    add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.blueprint_tracker
    add column if not exists date_saved timestamptz not null default now();

alter table public.blueprint_tracker
    add column if not exists blueprint_name text;

alter table public.blueprint_tracker
    add column if not exists blueprint_category text not null default 'Other';

alter table public.blueprint_tracker
    add column if not exists blueprint_status text not null default 'Owned';

alter table public.blueprint_tracker
    add column if not exists source_location text;

alter table public.blueprint_tracker
    add column if not exists copies_owned integer not null default 1;

alter table public.blueprint_tracker
    add column if not exists target_builds integer not null default 1;

alter table public.blueprint_tracker
    add column if not exists materials jsonb not null default '{}'::jsonb;

alter table public.blueprint_tracker
    add column if not exists notes text;

update public.blueprint_tracker
set copies_owned = 1
where copies_owned is null or copies_owned < 1;

update public.blueprint_tracker
set target_builds = 1
where target_builds is null or target_builds < 1;

update public.blueprint_tracker
set materials = '{}'::jsonb
where materials is null;

alter table public.blueprint_tracker
    drop constraint if exists blueprint_tracker_copies_owned_check;

alter table public.blueprint_tracker
    add constraint blueprint_tracker_copies_owned_check
    check (copies_owned >= 1);

alter table public.blueprint_tracker
    drop constraint if exists blueprint_tracker_target_builds_check;

alter table public.blueprint_tracker
    add constraint blueprint_tracker_target_builds_check
    check (target_builds >= 1);

create index if not exists blueprint_tracker_user_id_idx
    on public.blueprint_tracker(user_id);

create index if not exists blueprint_tracker_date_saved_idx
    on public.blueprint_tracker(date_saved desc);

alter table public.blueprint_tracker enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete
    on table public.blueprint_tracker
    to authenticated;

do $$
begin
    if to_regclass('public.blueprint_tracker_id_seq') is not null then
        execute 'grant usage, select on sequence public.blueprint_tracker_id_seq to authenticated';
    end if;
end
$$;

drop policy if exists "Users can read own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can insert own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can update own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can delete own blueprints"
on public.blueprint_tracker;

create policy "Users can read own blueprints"
on public.blueprint_tracker
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own blueprints"
on public.blueprint_tracker
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own blueprints"
on public.blueprint_tracker
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own blueprints"
on public.blueprint_tracker
for delete
to authenticated
using (auth.uid() = user_id);

commit;

-- Refresh the Supabase REST schema cache.
notify pgrst, 'reload schema';

-- Verification result. It should return one row with table_ready = true.
select
    to_regclass('public.blueprint_tracker') is not null as table_ready,
    has_table_privilege(
        'authenticated',
        'public.blueprint_tracker',
        'select,insert,update,delete'
    ) as authenticated_permissions_ready;


-- Commodity transaction tracker
begin;

create table if not exists public.commodity_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    commodity_name text not null,
    action text not null
        check (action in ('Bought', 'Sold', 'Lost / Destroyed')),
    quantity_scu numeric not null
        check (quantity_scu > 0),
    unit_price numeric not null default 0
        check (unit_price >= 0),
    fees numeric not null default 0
        check (fees >= 0),
    total_value numeric not null default 0
        check (total_value >= 0),
    origin text,
    destination text,
    shipment_reference text,
    notes text
);

create index if not exists commodity_transactions_user_id_idx
    on public.commodity_transactions(user_id);

create index if not exists commodity_transactions_date_saved_idx
    on public.commodity_transactions(date_saved desc);

create index if not exists commodity_transactions_commodity_name_idx
    on public.commodity_transactions(commodity_name);

alter table public.commodity_transactions enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete
    on table public.commodity_transactions
    to authenticated;

do $$
begin
    if to_regclass(
        'public.commodity_transactions_id_seq'
    ) is not null then
        execute
            'grant usage, select on sequence '
            'public.commodity_transactions_id_seq to authenticated';
    end if;
end
$$;

drop policy if exists "Users can read own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can insert own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can update own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can delete own commodity transactions"
on public.commodity_transactions;

create policy "Users can read own commodity transactions"
on public.commodity_transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own commodity transactions"
on public.commodity_transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own commodity transactions"
on public.commodity_transactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own commodity transactions"
on public.commodity_transactions
for delete
to authenticated
using (auth.uid() = user_id);

commit;

notify pgrst, 'reload schema';

select
    to_regclass(
        'public.commodity_transactions'
    ) is not null as table_ready,
    has_table_privilege(
        'authenticated',
        'public.commodity_transactions',
        'select,insert,update,delete'
    ) as authenticated_permissions_ready;


-- Profile picture storage
begin;

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'avatars',
    'avatars',
    true,
    2097152,
    array[
        'image/jpeg',
        'image/png',
        'image/webp'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can view own avatar objects"
on storage.objects;

drop policy if exists "Users can upload own avatars"
on storage.objects;

drop policy if exists "Users can update own avatars"
on storage.objects;

drop policy if exists "Users can delete own avatars"
on storage.objects;

create policy "Users can view own avatar objects"
on storage.objects
for select
to authenticated
using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can upload own avatars"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can update own avatars"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can delete own avatars"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
);

commit;

notify pgrst, 'reload schema';

select
    exists (
        select 1
        from storage.buckets
        where id = 'avatars'
          and public = true
    ) as avatar_bucket_ready;


-- Commodity math repair and synchronization
-- Star Citizen Tracker
-- Commodity math and compatibility repair
-- Run this entire file once in Supabase SQL Editor.

begin;

create table if not exists public.commodity_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    commodity_name text not null,
    action text not null default 'Bought',
    quantity_scu numeric not null default 0,
    unit_price numeric not null default 0,
    fees numeric not null default 0,
    total_value numeric not null default 0,
    cash_effect numeric not null default 0,
    origin text,
    destination text,
    shipment_reference text,
    notes text
);

alter table public.commodity_transactions
    add column if not exists date_saved timestamptz not null default now();

alter table public.commodity_transactions
    add column if not exists commodity_name text;

alter table public.commodity_transactions
    add column if not exists action text not null default 'Bought';

alter table public.commodity_transactions
    add column if not exists quantity_scu numeric not null default 0;

alter table public.commodity_transactions
    add column if not exists unit_price numeric not null default 0;

alter table public.commodity_transactions
    add column if not exists fees numeric not null default 0;

alter table public.commodity_transactions
    add column if not exists total_value numeric not null default 0;

alter table public.commodity_transactions
    add column if not exists cash_effect numeric not null default 0;

alter table public.commodity_transactions
    add column if not exists origin text;

alter table public.commodity_transactions
    add column if not exists destination text;

alter table public.commodity_transactions
    add column if not exists shipment_reference text;

alter table public.commodity_transactions
    add column if not exists notes text;

update public.commodity_transactions
set
    commodity_name = coalesce(
        nullif(trim(commodity_name), ''),
        'Unknown Commodity'
    ),
    action = case
        when lower(coalesce(action, '')) similar to
            '%(destroy|lost|loss)%'
            then 'Lost / Destroyed'
        when lower(coalesce(action, '')) similar to
            '%(sell|sold|sale)%'
            then 'Sold'
        when lower(coalesce(action, '')) similar to
            '%(buy|bought|purchas)%'
            then 'Bought'
        else 'Bought'
    end,
    quantity_scu = greatest(coalesce(quantity_scu, 0), 0),
    unit_price = greatest(coalesce(unit_price, 0), 0),
    fees = greatest(coalesce(fees, 0), 0),
    total_value = case
        when coalesce(quantity_scu, 0) > 0
         and coalesce(unit_price, 0) > 0
            then quantity_scu * unit_price
        else greatest(coalesce(total_value, 0), 0)
    end;

create or replace function public.sync_commodity_transaction_math()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.commodity_name := coalesce(
        nullif(trim(new.commodity_name), ''),
        'Unknown Commodity'
    );
    new.quantity_scu := greatest(coalesce(new.quantity_scu, 0), 0);
    new.unit_price := greatest(coalesce(new.unit_price, 0), 0);
    new.fees := greatest(coalesce(new.fees, 0), 0);

    if new.quantity_scu > 0 and new.unit_price > 0 then
        new.total_value := new.quantity_scu * new.unit_price;
    else
        new.total_value := greatest(coalesce(new.total_value, 0), 0);
    end if;

    new.cash_effect := case new.action
        when 'Sold' then new.total_value - new.fees
        when 'Bought' then -(new.total_value + new.fees)
        when 'Lost / Destroyed' then -(new.total_value + new.fees)
        else 0
    end;

    return new;
end;
$$;

drop trigger if exists commodity_transaction_math_trigger
on public.commodity_transactions;

create trigger commodity_transaction_math_trigger
before insert or update of
    commodity_name,
    action,
    quantity_scu,
    unit_price,
    fees,
    total_value
on public.commodity_transactions
for each row
execute function public.sync_commodity_transaction_math();

-- Re-run the trigger against existing rows.
update public.commodity_transactions
set unit_price = unit_price;

alter table public.commodity_transactions
    drop constraint if exists commodity_transactions_action_check;

alter table public.commodity_transactions
    add constraint commodity_transactions_action_check
    check (
        action in ('Bought', 'Sold', 'Lost / Destroyed')
    );

alter table public.commodity_transactions
    drop constraint if exists commodity_transactions_quantity_scu_check;

alter table public.commodity_transactions
    add constraint commodity_transactions_quantity_scu_check
    check (quantity_scu > 0);

alter table public.commodity_transactions
    drop constraint if exists commodity_transactions_unit_price_check;

alter table public.commodity_transactions
    add constraint commodity_transactions_unit_price_check
    check (unit_price >= 0);

alter table public.commodity_transactions
    drop constraint if exists commodity_transactions_fees_check;

alter table public.commodity_transactions
    add constraint commodity_transactions_fees_check
    check (fees >= 0);

alter table public.commodity_transactions enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete
    on table public.commodity_transactions
    to authenticated;

do $$
begin
    if to_regclass(
        'public.commodity_transactions_id_seq'
    ) is not null then
        execute
            'grant usage, select on sequence '
            'public.commodity_transactions_id_seq to authenticated';
    end if;
end
$$;

drop policy if exists "Users can read own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can insert own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can update own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can delete own commodity transactions"
on public.commodity_transactions;

create policy "Users can read own commodity transactions"
on public.commodity_transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own commodity transactions"
on public.commodity_transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own commodity transactions"
on public.commodity_transactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own commodity transactions"
on public.commodity_transactions
for delete
to authenticated
using (auth.uid() = user_id);

commit;

notify pgrst, 'reload schema';

select
    count(*) as commodity_records,
    coalesce(sum(total_value), 0) as verified_cargo_value,
    coalesce(sum(cash_effect), 0) as net_cash_effect,
    count(*) filter (
        where quantity_scu <= 0 or unit_price <= 0
    ) as incomplete_math_rows
from public.commodity_transactions;


-- Version 7 ore math repair
-- Star Citizen Tracker
-- Version 7: Ore quantity, unit-price, and cash-effect repair
-- Run this entire file once in Supabase SQL Editor.

begin;

alter table public.ore_transactions
    add column if not exists unit_price numeric not null default 0;

alter table public.ore_transactions
    add column if not exists cash_effect numeric not null default 0;

update public.ore_transactions
set
    action = case
        when lower(coalesce(action, '')) similar to '%(mine|extract)%'
            then 'Mined'
        when lower(coalesce(action, '')) similar to '%(buy|bought|purchas)%'
            then 'Bought'
        when lower(coalesce(action, '')) similar to '%(sell|sold|sale)%'
            then 'Sold'
        else action
    end,
    ore_name = coalesce(
        nullif(trim(ore_name), ''),
        'Unknown Resource'
    ),
    quantity_scu = greatest(coalesce(quantity_scu, 0), 0),
    unit_price = case
        when coalesce(unit_price, 0) > 0
            then unit_price
        when coalesce(quantity_scu, 0) > 0
         and coalesce(total_value, 0) > 0
            then total_value / quantity_scu
        else 0
    end,
    total_value = greatest(coalesce(total_value, 0), 0);

create or replace function public.sync_ore_transaction_math()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.ore_name := coalesce(
        nullif(trim(new.ore_name), ''),
        'Unknown Resource'
    );
    new.quantity_scu := greatest(
        coalesce(new.quantity_scu, 0),
        0
    );
    new.unit_price := greatest(
        coalesce(new.unit_price, 0),
        0
    );
    new.total_value := greatest(
        coalesce(new.total_value, 0),
        0
    );

    if new.quantity_scu > 0 and new.unit_price > 0 then
        new.total_value := new.quantity_scu * new.unit_price;
    elsif new.quantity_scu > 0
      and new.total_value > 0
      and new.unit_price <= 0 then
        new.unit_price := new.total_value / new.quantity_scu;
    end if;

    new.cash_effect := case new.action
        when 'Bought' then -new.total_value
        when 'Sold' then new.total_value
        else 0
    end;

    return new;
end;
$$;

drop trigger if exists ore_transaction_math_trigger
on public.ore_transactions;

create trigger ore_transaction_math_trigger
before insert or update of
    action,
    ore_name,
    quantity_scu,
    unit_price,
    total_value
on public.ore_transactions
for each row
execute function public.sync_ore_transaction_math();

-- Re-run the trigger against existing rows.
update public.ore_transactions
set total_value = total_value;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_action_check;

alter table public.ore_transactions
    add constraint ore_transactions_action_check
    check (action in ('Mined', 'Bought', 'Sold'));

alter table public.ore_transactions
    drop constraint if exists ore_transactions_quantity_scu_check;

alter table public.ore_transactions
    add constraint ore_transactions_quantity_scu_check
    check (quantity_scu >= 0);

alter table public.ore_transactions
    drop constraint if exists ore_transactions_unit_price_check;

alter table public.ore_transactions
    add constraint ore_transactions_unit_price_check
    check (unit_price >= 0);

alter table public.ore_transactions
    drop constraint if exists ore_transactions_total_value_check;

alter table public.ore_transactions
    add constraint ore_transactions_total_value_check
    check (total_value >= 0);

grant select, insert, update, delete
    on table public.ore_transactions
    to authenticated;

commit;

notify pgrst, 'reload schema';

select
    count(*) as ore_records,
    coalesce(sum(quantity_scu), 0) as entered_scu,
    coalesce(sum(total_value), 0) as verified_value,
    coalesce(sum(cash_effect), 0) as net_cash_effect,
    count(*) filter (
        where quantity_scu <= 0 and total_value > 0
    ) as records_missing_scu_quantity
from public.ore_transactions;


-- Version 8 ore schema-column and cache repair
-- Star Citizen Tracker
-- Version 8: Ore schema-column and PostgREST cache repair
--
-- Why this file exists:
-- The earlier Version 7 migration referenced quantity_scu before guaranteeing
-- that the column existed. If quantity_scu was missing, PostgreSQL aborted the
-- transaction and rolled the entire migration back.
--
-- Run this COMPLETE file once in the Supabase SQL Editor.

begin;

-- Remove the old trigger first so column repairs cannot conflict with it.
drop trigger if exists ore_transaction_math_trigger
on public.ore_transactions;

-- Guarantee that every column required by the current application exists
-- BEFORE any update, constraint, or trigger references it.
alter table public.ore_transactions
    add column if not exists quantity_scu numeric;

alter table public.ore_transactions
    add column if not exists unit_price numeric;

alter table public.ore_transactions
    add column if not exists cash_effect numeric;

alter table public.ore_transactions
    add column if not exists total_value numeric;

alter table public.ore_transactions
    add column if not exists location text;

alter table public.ore_transactions
    add column if not exists notes text;

-- Set defaults before enforcing NOT NULL.
alter table public.ore_transactions
    alter column quantity_scu set default 0;

alter table public.ore_transactions
    alter column unit_price set default 0;

alter table public.ore_transactions
    alter column cash_effect set default 0;

alter table public.ore_transactions
    alter column total_value set default 0;

-- Copy values from common legacy quantity column names when they exist.
do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'ore_transactions'
          and column_name = 'quantity'
    ) then
        execute $copy$
            update public.ore_transactions
            set quantity_scu = case
                when coalesce(quantity_scu, 0) > 0
                    then quantity_scu
                when trim(quantity::text)
                     ~ '^[+-]?[0-9]+([.][0-9]+)?$'
                    then greatest(quantity::numeric, 0)
                else 0
            end
        $copy$;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'ore_transactions'
          and column_name = 'scu'
    ) then
        execute $copy$
            update public.ore_transactions
            set quantity_scu = case
                when coalesce(quantity_scu, 0) > 0
                    then quantity_scu
                when trim(scu::text)
                     ~ '^[+-]?[0-9]+([.][0-9]+)?$'
                    then greatest(scu::numeric, 0)
                else 0
            end
        $copy$;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'ore_transactions'
          and column_name = 'amount_scu'
    ) then
        execute $copy$
            update public.ore_transactions
            set quantity_scu = case
                when coalesce(quantity_scu, 0) > 0
                    then quantity_scu
                when trim(amount_scu::text)
                     ~ '^[+-]?[0-9]+([.][0-9]+)?$'
                    then greatest(amount_scu::numeric, 0)
                else 0
            end
        $copy$;
    end if;
end
$$;

-- Remove constraints before normalizing legacy rows.
alter table public.ore_transactions
    drop constraint if exists ore_transactions_action_check;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_quantity_scu_check;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_unit_price_check;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_total_value_check;

-- Normalize existing records safely.
update public.ore_transactions
set
    action = case
        when lower(coalesce(action, '')) similar to '%(mine|extract)%'
            then 'Mined'
        when lower(coalesce(action, '')) similar to '%(buy|bought|purchas)%'
            then 'Bought'
        when lower(coalesce(action, '')) similar to '%(sell|sold|sale)%'
            then 'Sold'
        when action in ('Mined', 'Bought', 'Sold')
            then action
        else 'Mined'
    end,
    ore_name = coalesce(
        nullif(trim(ore_name), ''),
        'Unknown Resource'
    ),
    quantity_scu = greatest(coalesce(quantity_scu, 0), 0),
    unit_price = case
        when coalesce(unit_price, 0) > 0
            then greatest(unit_price, 0)
        when coalesce(quantity_scu, 0) > 0
         and coalesce(total_value, 0) > 0
            then greatest(total_value / quantity_scu, 0)
        else 0
    end,
    total_value = case
        when coalesce(quantity_scu, 0) > 0
         and coalesce(unit_price, 0) > 0
            then greatest(quantity_scu * unit_price, 0)
        else greatest(coalesce(total_value, 0), 0)
    end,
    cash_effect = case
        when action = 'Bought'
            then -greatest(coalesce(total_value, 0), 0)
        when action = 'Sold'
            then greatest(coalesce(total_value, 0), 0)
        else 0
    end;

-- Existing null values are repaired, so NOT NULL can now be enforced.
alter table public.ore_transactions
    alter column quantity_scu set not null;

alter table public.ore_transactions
    alter column unit_price set not null;

alter table public.ore_transactions
    alter column cash_effect set not null;

alter table public.ore_transactions
    alter column total_value set not null;

-- Recreate constraints.
alter table public.ore_transactions
    add constraint ore_transactions_action_check
    check (action in ('Mined', 'Bought', 'Sold'));

alter table public.ore_transactions
    add constraint ore_transactions_quantity_scu_check
    check (quantity_scu >= 0);

alter table public.ore_transactions
    add constraint ore_transactions_unit_price_check
    check (unit_price >= 0);

alter table public.ore_transactions
    add constraint ore_transactions_total_value_check
    check (total_value >= 0);

-- Database-side calculation guard.
create or replace function public.sync_ore_transaction_math()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.action := case
        when lower(coalesce(new.action, '')) similar to '%(mine|extract)%'
            then 'Mined'
        when lower(coalesce(new.action, '')) similar to '%(buy|bought|purchas)%'
            then 'Bought'
        when lower(coalesce(new.action, '')) similar to '%(sell|sold|sale)%'
            then 'Sold'
        when new.action in ('Mined', 'Bought', 'Sold')
            then new.action
        else 'Mined'
    end;

    new.ore_name := coalesce(
        nullif(trim(new.ore_name), ''),
        'Unknown Resource'
    );

    new.quantity_scu := greatest(
        coalesce(new.quantity_scu, 0),
        0
    );

    new.unit_price := greatest(
        coalesce(new.unit_price, 0),
        0
    );

    new.total_value := greatest(
        coalesce(new.total_value, 0),
        0
    );

    if new.quantity_scu > 0 and new.unit_price > 0 then
        new.total_value := new.quantity_scu * new.unit_price;
    elsif new.quantity_scu > 0
      and new.total_value > 0
      and new.unit_price <= 0 then
        new.unit_price := new.total_value / new.quantity_scu;
    end if;

    new.cash_effect := case new.action
        when 'Bought' then -new.total_value
        when 'Sold' then new.total_value
        else 0
    end;

    return new;
end;
$$;

create trigger ore_transaction_math_trigger
before insert or update of
    action,
    ore_name,
    quantity_scu,
    unit_price,
    total_value
on public.ore_transactions
for each row
execute function public.sync_ore_transaction_math();

-- Restore access and RLS policies.
alter table public.ore_transactions enable row level security;

grant usage on schema public to authenticated;

grant select, insert, update, delete
on table public.ore_transactions
to authenticated;

do $$
begin
    if to_regclass('public.ore_transactions_id_seq') is not null then
        execute
            'grant usage, select on sequence '
            'public.ore_transactions_id_seq to authenticated';
    end if;
end
$$;

drop policy if exists "Users can read own ore entries"
on public.ore_transactions;

drop policy if exists "Users can insert own ore entries"
on public.ore_transactions;

drop policy if exists "Users can update own ore entries"
on public.ore_transactions;

drop policy if exists "Users can delete own ore entries"
on public.ore_transactions;

create policy "Users can read own ore entries"
on public.ore_transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own ore entries"
on public.ore_transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own ore entries"
on public.ore_transactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own ore entries"
on public.ore_transactions
for delete
to authenticated
using (auth.uid() = user_id);

commit;

-- Force PostgREST/Supabase to refresh its schema cache.
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');

-- Verification result 1:
-- These four rows must appear after the migration.
select
    column_name,
    data_type,
    is_nullable,
    column_default
from information_schema.columns
where table_schema = 'public'
  and table_name = 'ore_transactions'
  and column_name in (
      'quantity_scu',
      'unit_price',
      'total_value',
      'cash_effect'
  )
order by column_name;

-- Verification result 2:
select
    count(*) as ore_records,
    coalesce(sum(quantity_scu), 0) as entered_scu,
    coalesce(sum(total_value), 0) as verified_value,
    coalesce(sum(cash_effect), 0) as net_cash_effect,
    count(*) filter (
        where quantity_scu <= 0 and total_value > 0
    ) as records_missing_scu_quantity
from public.ore_transactions;


-- Version 9 shared loot table
-- Star Citizen Tracker
-- Version 9: Shared loot table and item acquisition reference
--
-- Run this complete file once in Supabase SQL Editor.

begin;

create table if not exists public.loot_locations (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references auth.users(id)
        on delete cascade,
    date_saved timestamptz not null default now(),
    submitted_by text not null default 'Citizen',
    item_name text not null,
    category text not null default 'Other',
    acquisition_type text not null default 'Looted',
    system_name text not null default 'Unknown',
    location_name text not null,
    sub_location text,
    container_type text,
    rarity text not null default 'Unknown',
    mission_or_event text,
    patch_version text,
    verification_status text not null default 'Unverified',
    last_verified date,
    visibility text not null default 'Shared',
    notes text
);

-- Safe repair for partial or older deployments.
alter table public.loot_locations
    add column if not exists user_id uuid
        references auth.users(id)
        on delete cascade;

alter table public.loot_locations
    add column if not exists date_saved timestamptz
        not null default now();

alter table public.loot_locations
    add column if not exists submitted_by text
        not null default 'Citizen';

alter table public.loot_locations
    add column if not exists item_name text;

alter table public.loot_locations
    add column if not exists category text
        not null default 'Other';

alter table public.loot_locations
    add column if not exists acquisition_type text
        not null default 'Looted';

alter table public.loot_locations
    add column if not exists system_name text
        not null default 'Unknown';

alter table public.loot_locations
    add column if not exists location_name text;

alter table public.loot_locations
    add column if not exists sub_location text;

alter table public.loot_locations
    add column if not exists container_type text;

alter table public.loot_locations
    add column if not exists rarity text
        not null default 'Unknown';

alter table public.loot_locations
    add column if not exists mission_or_event text;

alter table public.loot_locations
    add column if not exists patch_version text;

alter table public.loot_locations
    add column if not exists verification_status text
        not null default 'Unverified';

alter table public.loot_locations
    add column if not exists last_verified date;

alter table public.loot_locations
    add column if not exists visibility text
        not null default 'Shared';

alter table public.loot_locations
    add column if not exists notes text;

update public.loot_locations
set
    submitted_by = coalesce(
        nullif(trim(submitted_by), ''),
        'Citizen'
    ),
    item_name = coalesce(
        nullif(trim(item_name), ''),
        'Unknown Item'
    ),
    category = coalesce(
        nullif(trim(category), ''),
        'Other'
    ),
    acquisition_type = case
        when acquisition_type in (
            'Looted',
            'Mission Reward',
            'Event Reward',
            'Crafted',
            'Salvaged',
            'Purchased - Special Vendor',
            'Subscriber / Pledge',
            'Other'
        ) then acquisition_type
        else 'Other'
    end,
    system_name = coalesce(
        nullif(trim(system_name), ''),
        'Unknown'
    ),
    location_name = coalesce(
        nullif(trim(location_name), ''),
        'Unknown'
    ),
    rarity = case
        when rarity in (
            'Common',
            'Uncommon',
            'Rare',
            'Very Rare',
            'Event / Limited',
            'Unknown'
        ) then rarity
        else 'Unknown'
    end,
    verification_status = case
        when verification_status in (
            'Verified',
            'Community Report',
            'Needs Recheck',
            'Unverified'
        ) then verification_status
        else 'Unverified'
    end,
    visibility = case
        when visibility in ('Shared', 'Private')
            then visibility
        else 'Shared'
    end;

alter table public.loot_locations
    alter column item_name set not null;

alter table public.loot_locations
    alter column location_name set not null;

alter table public.loot_locations
    drop constraint if exists
        loot_locations_acquisition_type_check;

alter table public.loot_locations
    add constraint loot_locations_acquisition_type_check
    check (
        acquisition_type in (
            'Looted',
            'Mission Reward',
            'Event Reward',
            'Crafted',
            'Salvaged',
            'Purchased - Special Vendor',
            'Subscriber / Pledge',
            'Other'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_rarity_check;

alter table public.loot_locations
    add constraint loot_locations_rarity_check
    check (
        rarity in (
            'Common',
            'Uncommon',
            'Rare',
            'Very Rare',
            'Event / Limited',
            'Unknown'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_verification_status_check;

alter table public.loot_locations
    add constraint
        loot_locations_verification_status_check
    check (
        verification_status in (
            'Verified',
            'Community Report',
            'Needs Recheck',
            'Unverified'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_visibility_check;

alter table public.loot_locations
    add constraint loot_locations_visibility_check
    check (visibility in ('Shared', 'Private'));

create index if not exists
    loot_locations_user_id_idx
on public.loot_locations(user_id);

create index if not exists
    loot_locations_item_name_idx
on public.loot_locations(item_name);

create index if not exists
    loot_locations_location_idx
on public.loot_locations(
    system_name,
    location_name
);

create index if not exists
    loot_locations_last_verified_idx
on public.loot_locations(last_verified desc);

alter table public.loot_locations
    enable row level security;

grant usage on schema public to authenticated;

grant select, insert, update, delete
on table public.loot_locations
to authenticated;

do $$
begin
    if to_regclass(
        'public.loot_locations_id_seq'
    ) is not null then
        execute
            'grant usage, select on sequence '
            'public.loot_locations_id_seq '
            'to authenticated';
    end if;
end
$$;

drop policy if exists
    "Authenticated users can read visible loot entries"
on public.loot_locations;

drop policy if exists
    "Users can insert own loot entries"
on public.loot_locations;

drop policy if exists
    "Users can update own loot entries"
on public.loot_locations;

drop policy if exists
    "Users can delete own loot entries"
on public.loot_locations;

-- Shared records can be read by every authenticated app user.
-- Private records can only be read by their creator.
create policy
    "Authenticated users can read visible loot entries"
on public.loot_locations
for select
to authenticated
using (
    visibility = 'Shared'
    or auth.uid() = user_id
);

create policy
    "Users can insert own loot entries"
on public.loot_locations
for insert
to authenticated
with check (auth.uid() = user_id);

create policy
    "Users can update own loot entries"
on public.loot_locations
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy
    "Users can delete own loot entries"
on public.loot_locations
for delete
to authenticated
using (auth.uid() = user_id);

commit;

notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');

select
    count(*) as loot_entries,
    count(*) filter (
        where visibility = 'Shared'
    ) as shared_entries,
    count(*) filter (
        where visibility = 'Private'
    ) as private_entries,
    count(*) filter (
        where verification_status = 'Verified'
    ) as verified_entries
from public.loot_locations;

-- Refresh PostgREST after schema changes.
NOTIFY pgrst, 'reload schema';
