-- Star Citizen Tracker
-- Version 9: Shared loot table and item acquisition reference
--
-- Run this complete file once in Supabase SQL Editor.

begin;

create table if not exists public.loot_locations (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references auth.users(id)
        on delete cascade,
    date_saved timestamptz not null default now(),
    submitted_by text not null default 'Citizen',
    item_name text not null,
    category text not null default 'Other',
    acquisition_type text not null default 'Looted',
    system_name text not null default 'Unknown',
    location_name text not null,
    sub_location text,
    container_type text,
    rarity text not null default 'Unknown',
    mission_or_event text,
    patch_version text,
    verification_status text not null default 'Unverified',
    last_verified date,
    visibility text not null default 'Shared',
    notes text
);

-- Safe repair for partial or older deployments.
alter table public.loot_locations
    add column if not exists user_id uuid
        references auth.users(id)
        on delete cascade;

alter table public.loot_locations
    add column if not exists date_saved timestamptz
        not null default now();

alter table public.loot_locations
    add column if not exists submitted_by text
        not null default 'Citizen';

alter table public.loot_locations
    add column if not exists item_name text;

alter table public.loot_locations
    add column if not exists category text
        not null default 'Other';

alter table public.loot_locations
    add column if not exists acquisition_type text
        not null default 'Looted';

alter table public.loot_locations
    add column if not exists system_name text
        not null default 'Unknown';

alter table public.loot_locations
    add column if not exists location_name text;

alter table public.loot_locations
    add column if not exists sub_location text;

alter table public.loot_locations
    add column if not exists container_type text;

alter table public.loot_locations
    add column if not exists rarity text
        not null default 'Unknown';

alter table public.loot_locations
    add column if not exists mission_or_event text;

alter table public.loot_locations
    add column if not exists patch_version text;

alter table public.loot_locations
    add column if not exists verification_status text
        not null default 'Unverified';

alter table public.loot_locations
    add column if not exists last_verified date;

alter table public.loot_locations
    add column if not exists visibility text
        not null default 'Shared';

alter table public.loot_locations
    add column if not exists notes text;

update public.loot_locations
set
    submitted_by = coalesce(
        nullif(trim(submitted_by), ''),
        'Citizen'
    ),
    item_name = coalesce(
        nullif(trim(item_name), ''),
        'Unknown Item'
    ),
    category = coalesce(
        nullif(trim(category), ''),
        'Other'
    ),
    acquisition_type = case
        when acquisition_type in (
            'Looted',
            'Mission Reward',
            'Event Reward',
            'Crafted',
            'Salvaged',
            'Purchased - Special Vendor',
            'Subscriber / Pledge',
            'Other'
        ) then acquisition_type
        else 'Other'
    end,
    system_name = coalesce(
        nullif(trim(system_name), ''),
        'Unknown'
    ),
    location_name = coalesce(
        nullif(trim(location_name), ''),
        'Unknown'
    ),
    rarity = case
        when rarity in (
            'Common',
            'Uncommon',
            'Rare',
            'Very Rare',
            'Event / Limited',
            'Unknown'
        ) then rarity
        else 'Unknown'
    end,
    verification_status = case
        when verification_status in (
            'Verified',
            'Community Report',
            'Needs Recheck',
            'Unverified'
        ) then verification_status
        else 'Unverified'
    end,
    visibility = case
        when visibility in ('Shared', 'Private')
            then visibility
        else 'Shared'
    end;

alter table public.loot_locations
    alter column item_name set not null;

alter table public.loot_locations
    alter column location_name set not null;

alter table public.loot_locations
    drop constraint if exists
        loot_locations_acquisition_type_check;

alter table public.loot_locations
    add constraint loot_locations_acquisition_type_check
    check (
        acquisition_type in (
            'Looted',
            'Mission Reward',
            'Event Reward',
            'Crafted',
            'Salvaged',
            'Purchased - Special Vendor',
            'Subscriber / Pledge',
            'Other'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_rarity_check;

alter table public.loot_locations
    add constraint loot_locations_rarity_check
    check (
        rarity in (
            'Common',
            'Uncommon',
            'Rare',
            'Very Rare',
            'Event / Limited',
            'Unknown'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_verification_status_check;

alter table public.loot_locations
    add constraint
        loot_locations_verification_status_check
    check (
        verification_status in (
            'Verified',
            'Community Report',
            'Needs Recheck',
            'Unverified'
        )
    );

alter table public.loot_locations
    drop constraint if exists
        loot_locations_visibility_check;

alter table public.loot_locations
    add constraint loot_locations_visibility_check
    check (visibility in ('Shared', 'Private'));

create index if not exists
    loot_locations_user_id_idx
on public.loot_locations(user_id);

create index if not exists
    loot_locations_item_name_idx
on public.loot_locations(item_name);

create index if not exists
    loot_locations_location_idx
on public.loot_locations(
    system_name,
    location_name
);

create index if not exists
    loot_locations_last_verified_idx
on public.loot_locations(last_verified desc);

alter table public.loot_locations
    enable row level security;

grant usage on schema public to authenticated;

grant select, insert, update, delete
on table public.loot_locations
to authenticated;

do $$
begin
    if to_regclass(
        'public.loot_locations_id_seq'
    ) is not null then
        execute
            'grant usage, select on sequence '
            'public.loot_locations_id_seq '
            'to authenticated';
    end if;
end
$$;

drop policy if exists
    "Authenticated users can read visible loot entries"
on public.loot_locations;

drop policy if exists
    "Users can insert own loot entries"
on public.loot_locations;

drop policy if exists
    "Users can update own loot entries"
on public.loot_locations;

drop policy if exists
    "Users can delete own loot entries"
on public.loot_locations;

-- Shared records can be read by every authenticated app user.
-- Private records can only be read by their creator.
create policy
    "Authenticated users can read visible loot entries"
on public.loot_locations
for select
to authenticated
using (
    visibility = 'Shared'
    or auth.uid() = user_id
);

create policy
    "Users can insert own loot entries"
on public.loot_locations
for insert
to authenticated
with check (auth.uid() = user_id);

create policy
    "Users can update own loot entries"
on public.loot_locations
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy
    "Users can delete own loot entries"
on public.loot_locations
for delete
to authenticated
using (auth.uid() = user_id);

commit;

notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');

select
    count(*) as loot_entries,
    count(*) filter (
        where visibility = 'Shared'
    ) as shared_entries,
    count(*) filter (
        where visibility = 'Private'
    ) as private_entries,
    count(*) filter (
        where verification_status = 'Verified'
    ) as verified_entries
from public.loot_locations;
