-- Star Citizen Tracker
-- Commodity buy, sell, and lost-shipment tracker
-- Run this entire file once in Supabase SQL Editor.

begin;

create table if not exists public.commodity_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    commodity_name text not null,
    action text not null
        check (action in ('Bought', 'Sold', 'Lost / Destroyed')),
    quantity_scu numeric not null
        check (quantity_scu > 0),
    unit_price numeric not null default 0
        check (unit_price >= 0),
    fees numeric not null default 0
        check (fees >= 0),
    total_value numeric not null default 0
        check (total_value >= 0),
    origin text,
    destination text,
    shipment_reference text,
    notes text
);

create index if not exists commodity_transactions_user_id_idx
    on public.commodity_transactions(user_id);

create index if not exists commodity_transactions_date_saved_idx
    on public.commodity_transactions(date_saved desc);

create index if not exists commodity_transactions_commodity_name_idx
    on public.commodity_transactions(commodity_name);

alter table public.commodity_transactions enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete
    on table public.commodity_transactions
    to authenticated;

do $$
begin
    if to_regclass(
        'public.commodity_transactions_id_seq'
    ) is not null then
        execute
            'grant usage, select on sequence '
            'public.commodity_transactions_id_seq to authenticated';
    end if;
end
$$;

drop policy if exists "Users can read own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can insert own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can update own commodity transactions"
on public.commodity_transactions;

drop policy if exists "Users can delete own commodity transactions"
on public.commodity_transactions;

create policy "Users can read own commodity transactions"
on public.commodity_transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own commodity transactions"
on public.commodity_transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own commodity transactions"
on public.commodity_transactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own commodity transactions"
on public.commodity_transactions
for delete
to authenticated
using (auth.uid() = user_id);

commit;

notify pgrst, 'reload schema';

select
    to_regclass(
        'public.commodity_transactions'
    ) is not null as table_ready,
    has_table_privilege(
        'authenticated',
        'public.commodity_transactions',
        'select,insert,update,delete'
    ) as authenticated_permissions_ready;
