-- Star Citizen Tracker v1.3
-- Saved starmap routes shared by the Streamlit app and Windows companion.

begin;

create table if not exists public.saved_routes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    route_name text not null,
    route_data jsonb not null default '[]'::jsonb,
    notes text not null default '',
    is_active boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists saved_routes_user_id_idx
    on public.saved_routes(user_id);

create index if not exists saved_routes_active_idx
    on public.saved_routes(user_id, is_active);

alter table public.saved_routes enable row level security;

drop policy if exists "Users can read own saved routes" on public.saved_routes;
drop policy if exists "Users can insert own saved routes" on public.saved_routes;
drop policy if exists "Users can update own saved routes" on public.saved_routes;
drop policy if exists "Users can delete own saved routes" on public.saved_routes;

create policy "Users can read own saved routes"
on public.saved_routes for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own saved routes"
on public.saved_routes for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own saved routes"
on public.saved_routes for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own saved routes"
on public.saved_routes for delete to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.set_saved_routes_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists saved_routes_set_updated_at on public.saved_routes;
create trigger saved_routes_set_updated_at
before update on public.saved_routes
for each row execute function public.set_saved_routes_updated_at();

commit;

notify pgrst, 'reload schema';
