-- Run this once in Supabase SQL Editor for an existing deployment.

create table if not exists public.blueprint_tracker (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    blueprint_name text not null,
    blueprint_category text not null default 'Other',
    blueprint_status text not null default 'Owned',
    source_location text,
    copies_owned integer not null default 1 check (copies_owned >= 1),
    target_builds integer not null default 1 check (target_builds >= 1),
    materials jsonb not null default '{}'::jsonb,
    notes text
);

create index if not exists blueprint_tracker_user_id_idx
    on public.blueprint_tracker(user_id);

create index if not exists blueprint_tracker_date_saved_idx
    on public.blueprint_tracker(date_saved desc);

alter table public.blueprint_tracker enable row level security;

drop policy if exists "Users can read own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can insert own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can update own blueprints"
on public.blueprint_tracker;

drop policy if exists "Users can delete own blueprints"
on public.blueprint_tracker;

create policy "Users can read own blueprints"
on public.blueprint_tracker
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own blueprints"
on public.blueprint_tracker
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own blueprints"
on public.blueprint_tracker
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own blueprints"
on public.blueprint_tracker
for delete
to authenticated
using ((select auth.uid()) = user_id);
